//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.08 at 07:13:03 PM ACST 
//


package com.glenfordham.webserver.automationserver.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.glenfordham.automationserver.configjaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.glenfordham.automationserver.configjaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createAutomationServer() {
        return new Config();
    }

    /**
     * Create an instance of {@link Config.Broadlink }
     * 
     */
    public Config.Broadlink createAutomationServerBroadlink() {
        return new Config.Broadlink();
    }

    /**
     * Create an instance of {@link Config.Broadlink.Requests }
     * 
     */
    public Config.Broadlink.Requests createAutomationServerBroadlinkRequests() {
        return new Config.Broadlink.Requests();
    }

    /**
     * Create an instance of {@link Config.Broadlink.Devices }
     * 
     */
    public Config.Broadlink.Devices createAutomationServerBroadlinkDevices() {
        return new Config.Broadlink.Devices();
    }

    /**
     * Create an instance of {@link Config.CommandLine }
     * 
     */
    public Config.CommandLine createAutomationServerCommandLine() {
        return new Config.CommandLine();
    }

    /**
     * Create an instance of {@link Config.CommandLine.Requests }
     * 
     */
    public Config.CommandLine.Requests createAutomationServerCommandLineRequests() {
        return new Config.CommandLine.Requests();
    }

    /**
     * Create an instance of {@link Config.Email }
     * 
     */
    public Config.Email createAutomationServerEmail() {
        return new Config.Email();
    }

    /**
     * Create an instance of {@link Config.Email.Requests }
     * 
     */
    public Config.Email.Requests createAutomationServerEmailRequests() {
        return new Config.Email.Requests();
    }

    /**
     * Create an instance of {@link Config.Gpio }
     * 
     */
    public Config.Gpio createAutomationServerGpio() {
        return new Config.Gpio();
    }

    /**
     * Create an instance of {@link Config.Gpio.Requests }
     * 
     */
    public Config.Gpio.Requests createAutomationServerGpioRequests() {
        return new Config.Gpio.Requests();
    }

    /**
     * Create an instance of {@link Config.Gpio.Requests.Request }
     * 
     */
    public Config.Gpio.Requests.Request createAutomationServerGpioRequestsRequest() {
        return new Config.Gpio.Requests.Request();
    }

    /**
     * Create an instance of {@link Config.Carport }
     * 
     */
    public Config.Carport createAutomationServerCarport() {
        return new Config.Carport();
    }

    /**
     * Create an instance of {@link Config.Carport.Requests }
     * 
     */
    public Config.Carport.Requests createAutomationServerCarportRequests() {
        return new Config.Carport.Requests();
    }

    /**
     * Create an instance of {@link Config.Carport.RequestTypes }
     * 
     */
    public Config.Carport.RequestTypes createAutomationServerCarportRequestTypes() {
        return new Config.Carport.RequestTypes();
    }

    /**
     * Create an instance of {@link Config.Broadlink.Requests.Request }
     * 
     */
    public Config.Broadlink.Requests.Request createAutomationServerBroadlinkRequestsRequest() {
        return new Config.Broadlink.Requests.Request();
    }

    /**
     * Create an instance of {@link Config.Broadlink.Devices.Device }
     * 
     */
    public Config.Broadlink.Devices.Device createAutomationServerBroadlinkDevicesDevice() {
        return new Config.Broadlink.Devices.Device();
    }

    /**
     * Create an instance of {@link Config.CommandLine.Requests.Request }
     * 
     */
    public Config.CommandLine.Requests.Request createAutomationServerCommandLineRequestsRequest() {
        return new Config.CommandLine.Requests.Request();
    }

    /**
     * Create an instance of {@link Config.Email.Requests.Request }
     * 
     */
    public Config.Email.Requests.Request createAutomationServerEmailRequestsRequest() {
        return new Config.Email.Requests.Request();
    }

    /**
     * Create an instance of {@link Config.Gpio.Requests.Request.Write }
     * 
     */
    public Config.Gpio.Requests.Request.Write createAutomationServerGpioRequestsRequestWrite() {
        return new Config.Gpio.Requests.Request.Write();
    }

    /**
     * Create an instance of {@link Config.Gpio.Requests.Request.Read }
     * 
     */
    public Config.Gpio.Requests.Request.Read createAutomationServerGpioRequestsRequestRead() {
        return new Config.Gpio.Requests.Request.Read();
    }

    /**
     * Create an instance of {@link Config.Carport.Requests.Request }
     * 
     */
    public Config.Carport.Requests.Request createAutomationServerCarportRequestsRequest() {
        return new Config.Carport.Requests.Request();
    }

    /**
     * Create an instance of {@link Config.Carport.RequestTypes.RequestType }
     * 
     */
    public Config.Carport.RequestTypes.RequestType createAutomationServerCarportRequestTypesRequestType() {
        return new Config.Carport.RequestTypes.RequestType();
    }

}
