name: Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Fix Gradle
        run: gradle wrapper --stacktrace
      - name: Build Fat Jar
        run: ./gradlew shadowJar --stacktrace
      - name: Build Zips
        run: ./gradlew runtimeZip --stacktrace
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          bodyFile: release-notes.MD
          omitNameDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/libs/automation-server*all.jar,build/automation-server*.zip"
